### ISSUE TITLE
Word lessons not working

### ISSUE THREAD

**Issue by pumbapop** [sugarlabs/typing-turtle-activity#20]
Any word lessons are not showing the words to type. Key lessons show a green box with which key to type, but word lessons only show the instruction text.

**Comment by quozl** [comment]
I've tried v32 and HEAD; word lessons show words in balloons.  What version did you try?  What is the exact lesson name?

**Comment by pumbapop** [comment]
I'm on version 32, "The Home Row" lesson. Step 3 is where it stops working,
and the problem happens with any step that is a "Words" step. Even if I try
typing the answer without the prompt, it will not progress past that step.

**Comment by chimosky** [comment]
@pumbapop thanks for reporting, error was caused when activity was ported to python3.
