### ISSUE TITLE
PyGObject PyGIWarnings for Gtk and PaingoCairo

### ISSUE THREAD

**Issue by quozl** [sugarlabs/typing-turtle-activity#8]
Seen on Fedora 31.

**Comment by ayushnawal** [comment]
I think we can close this issue now

**Comment by chimosky** [comment]
@ayushnawal did you test on fedora 31 and didn't get the warnings?

**Comment by quozl** [comment]
I think testing on Fedora 31 would be difficult given the missing Python 3 support.  I've checked the `require_version` calls of the main program do mention Gtk and PangoCairo now.  However there are more calls in the other files that aren't necessary.

**Comment by ayushnawal** [comment]
> I've checked the require_version calls of the main program do mention Gtk and PangoCairo now

No @chimosky , didn't test on fedora 31 but as James said, I also saw that the `require_version` calls were present and I was not getting any such warning on my system too.
